name: postgresql-migration
version: 1.0.0
synopsis: Postgres Migration Library
description: This package offers easy migration library for Postgres database
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2018 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/haskellify/postgresql-migration
git: git@github.com:haskellify/postgresql-migration.git
bug-reports: https://github.com/haskellify/postgresql-migration/issues
tested-with: GHC==9.4.4
library:
  source-dirs: lib
  when:
  - condition: os(darwin)
    then:
      ghc-options: -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
  dependencies:
  - base
  - monad-logger
  - mtl
  - postgresql-simple
  - postgresql-libpq
  - resource-pool
  - text
  - time
  default-extensions:
    - OverloadedStrings
    - DeriveGeneric
